### ISSUE TITLE
Why not build a vagrant box and publish it?

### ISSUE THREAD

**Issue by dbarrosop** [jerearista/vagrant-veos#1]
Awesome instructions, very informative and useful to learn how to build a vagrant box. However, why not publish a vagrant box? That would be very useful and time saving : )

**Comment by jerearista** [comment]
Be on the lookout.  Working out details of adding this in to the release process.

**Comment by dbarrosop** [comment]
Awesome : )

**Comment by jerearista** [comment]
Wow, I didn't mean to leave this stale for so long.   For anyone who hasn't found it already,  virtualbox.box files for vEOS-lab can be found in the Software Downloads section of http://arista.com/ for current releases.
