### ISSUE TITLE
VBOX_E_IPRT_ERROR For ISO

### ISSUE THREAD

**Issue by cretz** [jerearista/vagrant-veos#4]
Whether I use this repository, the packer-veos repository, or just try all steps with VBoxManage myself and the Vagrant exporter, I always get this on Windows:

```
PS C:\redacted\vEOS-test> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'vEOS-4.15.0F'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "C:/Users/cretz/.vagrant.d/boxes/vEOS-4.15.0F/0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "vEOS-4.15.0F_1443719553518_58838", "--vsys", "0", "--unit", "13", "--disk", "C:\\Users\\cretz\\VirtualBox VMs\\vEOS-4.15.0F_1443719553518_58838\\vEOS-4.1
5.0F-disk2.iso", "--vsys", "0", "--unit", "14", "--disk", "C:\\Users\\cretz\\VirtualBox VMs\\vEOS-4.15.0F_1443719553518_58838\\vEOS-4.15.0F-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting C:\Users\cretz\.vagrant.d\boxes\vEOS-4.15.0F\0\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_OBJECT_NOT_FOUND
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not get the storage format of the medium 'C:\Users\cretz\VirtualBox VMs\vEOS-4.15.0F_1443719553518_58838\vEOS-4.15.0F-disk2.iso' (VERR_SHARING_VIOLATION)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 877 of file VBoxManageAppliance.cpp
```

I have tried all combinations of ISO's and VMDK downloads. The research I do mentions the ISO being corrupt, yet the entire packer build works properly. Any ideas? I am on the latest vagrant, packer, and virtualbox and despite my exhaustive Googling I am unable to find a remedy.

**Comment by jerearista** [comment]
I think the root of the issue is likely closer to the VERR_SHARING_VIOLATION code.  I'm not very familiar with Windows but can you confirm that there are no other virtualbox processes running at the time? (anything containing "VBox" in the name)   Could you try these actions immediately after a reboot, before starting any other applications?

You want Aboot-veos-2.1.0.iso to go with vEOS-lab-4.15.0F.vmdk.

**Comment by cretz** [comment]
I have confirmed both and have used those ISO's and the error persists. You are correct, that is the most specific code describing the problem and it occurs on other Windows hosts such as mine. I concede that this is likely specific to my Windows 7 workstation and will close this whilst eagerly anticipating #1.
