### ISSUE TITLE
Port forward API issues

### ISSUE THREAD

**Issue by jonlangemak** [jerearista/vagrant-veos#5]
First off - Thanks for doing this.  As a new user to Vagrant, it's helped me get started, but I'm getting hung up on a couple of things.  I'd like to use the setup to test making eAPI calls against the API by doing a port forward like you suggest in the documentation.  However, when I try it on SSL, I get the following SSL error when I execute basic eAPI calls.

<pre><code>ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)</pre></code>

The code Im trying to execute is pretty basic...

<pre><code>switch = Server("https://vagrant:vagrant@localhost:8443/command-api")
response = switch.runCmds(1, ["show ip route"])
print json.dumps(response, indent=4, sort_keys=True)</pre></code>

Im doing this on my Mac running El Capitan and I have the 2.7.10 Python install (with home brew).  So after some messing around, I noticed that I couldnt browse to the URL explorer either by hitting https://localhost:8443.  Should this work?

After noticing that I enabled the API server on HTTP and tried the calls from Python using that and I get nothing.  I alos cant browse to API explorer on HTTP either.  

Any thoughts you have would be great.  Thanks!

**Comment by jerearista** [comment]
I'm glad you find this useful.

First, manually, try https://localhost:8443/explorer.html from your browser.

Second, the issue with certificate verify failing has to do with 2 things:  the built-in server on EOS uses self-signed certificates and Python made certificate validation the default last year. See https://www.python.org/dev/peps/pep-0476/ which has some suggestions for working with unverified contexts.

**Comment by jonlangemak** [comment]
Thanks for the clarification.  I must have been typing the URL wrong, but I can now browse to the explorer on 443 so that is working.  A couple more questions if you don't mind (if theres another forum for this I'd be glad to ask there)

Can this be configured for HTTP rather than HTTPS?  I added a Vagrant port forward command for 8080 and then manually configured the command API in the switch config to allow for communication on HTTP for that port.  When I try to browse to the explorer via HTTP it just spins.  Is there something else that needs to be done for this to work on HTTP?

Admittedly, Im not a SSL or Python expert (just getting started) so while I see the problem that this is using a self signed cert, Im not clear on how to fix it.  I imported the certificate into my local cert trust and Im no longer getting a cert error in the browser.  However - my Python code is still failing.  It sounds like I need to use a different context, but Im not sure how to do that with the jsonrpclib library I'm using.  So what Im wondering is what code (fix) you're using for this to work?  Are you using a different package?  Or what does a eAPI call look like for you that's working?

Thanks for your help.  I'd love to document this if we can find a solution to make it easier for others getting started here.  

Let me know

**Comment by jerearista** [comment]
In the EOS CLI, you can configure eAPI to use HTTP instead of HTTPS with the following:

```
Arista(config)# management api http-commands
Arista(config-mgmt-api-http-cmds)#protocol http
Arista(config-mgmt-api-http-cmds)#no shutdown
```

While not pretty, adding the following code to your script will disable certificate checking during that run:

```
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

You might, also, look at [pyeapi](https://github.com/arista-eosplus/pyeapi) if you prefer a more programatic interface to the CLI you use with jsonrpclib.
