### ISSUE TITLE
Error with vagrant up with EOS-4.15.5M

### ISSUE THREAD

**Issue by tharpie** [jerearista/vagrant-veos#7]
I'm getting the following errors when trying to load 4.15.5M. 

Interpreting C:\Users\Tharp Family.vagrant.d\boxes\vEOS-lab-4.15.5M\0\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_OBJECT_NOT_FOUND
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not get the storage format of the medium 'C:\Users\Tharp Family\VirtualBox VMs\vEOS-4.15.5M_1462723112437_40437\vEOS-4.15.5M-disk2.iso' (VERR_SHARING_VIOLATION)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 877 of file VBoxManageAppliance.cpp

Any ideas of what could be going on?

**Comment by jerearista** [comment]
This looks eerily similar to #4, found on Window 7.   There are also a number of references to VERR_SHARING_VIOLATION found and addressed in the VirtualBox forums but there's don't seem to be any clear winners.   

On the up side, you should be able to download the pre-packaged box from http://arista.com/  --> Software Downloads --> vEOS  --> vEOS-lab-4.15.5M-virtualbox.box.   Please let me know if you have any issues with that box or need further assistance.

**Comment by jcosentino** [comment]
I ran into this issue on Windows 10, Virtualbox 5.0.22, Vagrant 1.8.4
I ran "vagrant up", and got:
"
Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting C:\Users\John.vagrant.d\boxes\ubuntu-VAGRANTSLASH-trusty64\2016062
1.0.0\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\John\Virtu
alBox VMs\ubuntu-cloudimg-trusty-vagrant-amd64_1467168167978_8384\box-disk1.vmdk
' (VERR_ZIP_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component A
pplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(s
truct HandlerArg *)" at line 877 of file VBoxManageAppliance.cpp
"
Is there any solution?

**Comment by prokosa** [comment]
Omg, just delete olders machines

**Comment by jerearista** [comment]
Appears to be a Windows-VirtualBox issues.    Recommend just downloading the latest pre-built images from http://arista.com/
